create table "public"."posts_tags" (
    "created_at" timestamp with time zone not null default now(),
    "post_id" bigint not null,
    "tag_id" bigint not null
);


alter table "public"."posts_tags" enable row level security;

create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "user_id" uuid not null
);


alter table "public"."tags" enable row level security;

alter table "public"."comments" add column "post_id" bigint not null;

alter table "public"."users" add column "full_name" text;

CREATE UNIQUE INDEX posts_tags_pkey ON public.posts_tags USING btree (post_id, tag_id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."posts_tags" add constraint "posts_tags_pkey" PRIMARY KEY using index "posts_tags_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."comments" add constraint "comments_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_post_id_fkey";

alter table "public"."posts_tags" add constraint "posts_tags_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE not valid;

alter table "public"."posts_tags" validate constraint "posts_tags_post_id_fkey";

alter table "public"."posts_tags" add constraint "posts_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE not valid;

alter table "public"."posts_tags" validate constraint "posts_tags_tag_id_fkey";

alter table "public"."tags" add constraint "tags_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."tags" validate constraint "tags_user_id_fkey";

grant delete on table "public"."posts_tags" to "anon";

grant insert on table "public"."posts_tags" to "anon";

grant references on table "public"."posts_tags" to "anon";

grant select on table "public"."posts_tags" to "anon";

grant trigger on table "public"."posts_tags" to "anon";

grant truncate on table "public"."posts_tags" to "anon";

grant update on table "public"."posts_tags" to "anon";

grant delete on table "public"."posts_tags" to "authenticated";

grant insert on table "public"."posts_tags" to "authenticated";

grant references on table "public"."posts_tags" to "authenticated";

grant select on table "public"."posts_tags" to "authenticated";

grant trigger on table "public"."posts_tags" to "authenticated";

grant truncate on table "public"."posts_tags" to "authenticated";

grant update on table "public"."posts_tags" to "authenticated";

grant delete on table "public"."posts_tags" to "service_role";

grant insert on table "public"."posts_tags" to "service_role";

grant references on table "public"."posts_tags" to "service_role";

grant select on table "public"."posts_tags" to "service_role";

grant trigger on table "public"."posts_tags" to "service_role";

grant truncate on table "public"."posts_tags" to "service_role";

grant update on table "public"."posts_tags" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";


