name: CI

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Run ESLint
              run: |
                  npm ci
                  npm run lint

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - run: npm run db:start
            - run: npm run db:lint
            - run: npm run db:test

            - name: Verify generated types are checked in
              run: |
                  supabase gen types typescript --local > types.gen.ts
                  if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
                    echo "Detected uncommitted changes after build. See status below:"
                    git diff
                    exit 1
                  fi
