name: Deploy Supabase

on:
    push:
        branches:
            - main
        paths:
            - supabase/**
    workflow_dispatch:

jobs:
    Staging:
        runs-on: ubuntu-latest
        environment: Staging
        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
            SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - run: supabase link --project-ref $SUPABASE_PROJECT_ID
            - run: supabase db push
    Production:
        runs-on: ubuntu-latest
        environment: Production
        needs: Staging
        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
            SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

        steps:
            - uses: actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            - run: supabase link --project-ref $SUPABASE_PROJECT_ID
            - run: supabase db push
