name: Update database types
on:
    push:
        branches:
            - main
        paths:
            - supabase/**
    workflow_dispatch:


jobs:
    build:
      runs-on: ubuntu-latest
      environment: Staging
      if: github.head_ref != 'supabot**'
      steps:
      - uses: lyqht/generate-supabase-db-types-github-action@main
        with:
          SUPABASE_REF_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          OUTPUT_PATH: src/types/supabase.ts